language: python
python: "3.7"

sudo: true

install: true

service:
  - mysql

before_install: 
  - export TROD_DB_URL=mysql://root:flzxsqc1234567@gz-cdb-j9riel8h.sql.tencentcdb.com:60684/trod
  - pip install aiomysql
  - pip install pytz
  - pip install pytest pytest-asyncio pytest-cov
  - pip install coveralls coverage
  - pip install pylint

script: 
  - pylint trod --jobs=4 --reports=yes
  - pytest -svq --color=yes --cov=trod tests/

after_success:
  - coveralls
